[package]
name = "cynic-cli"
keywords = ["graphql", "client", "introspection", "cli"]
readme = "README.md"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cynic"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
cynic = { path = "../cynic", version = "3.2.0", features = ["http-reqwest-blocking"] }
cynic-introspection = { path = "../cynic-introspection", version = "3.2.0" }
reqwest = { version = "0.11", features = ["blocking"] }
thiserror = "1"

[dev-dependencies]
trycmd = "0.14"
