name: Build & Test Rust

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

env:
  COLUMNS: 250
  CARGO_INCREMENTAL: 0
  # TODO: Would be nice to disable warnings here too, but there are too many of them.
  RUSTFLAGS: "-W rust-2021-compatibility"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci
  CI: 1

jobs:
  check-format:
    # Skip draft release PRs
    if: ${{ github.actor_id != '166170668' || github.event_name != 'pull_request' || github.event.pull_request.draft == false }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt
      - name: Check format
        run: cargo fmt --all --check

  build-rust:
    # Skip draft release PRs
    if: ${{ github.actor_id != '166170668' || github.event_name != 'pull_request' || github.event.pull_request.draft == false }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Build cynic
        run: cargo build --workspace --all-features

      - name: Install nextest
        shell: bash
        run: |
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Build tests
        shell: bash
        run: |
          cargo nextest run --workspace --all-features --no-run

      - name: Run tests
        shell: bash
        run: |
          cargo nextest run --workspace --all-features

      - name: Build example tests
        shell: bash
        run: |
          cargo nextest run --workspace --examples --no-run

      - name: Run example tests
        shell: bash
        run: |
          cargo nextest run --workspace --examples

      - name: Build & run doctests
        shell: bash
        run: |
          cargo test --doc --workspace
